# Generated by Django 5.2.6 on 2025-11-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_options_alter_comment_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
