# Generated by Django 5.2.6 on 2025-11-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
