# Generated by Django 5.2.6 on 2025-11-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="active",
        ),
    ]
